jobs:
  terraform:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.x
      - name: Initialize Terraform working directory
        run: terraform init
      - name: Check if the input is formatted
        run: terraform fmt -check
      - name: Check whether the configuration is valid
        run: terraform validate
      - if: ${{ github.event_name == 'pull_request' }}
        name: Show changes required by the current configuration
        run: terraform plan
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Create or update infrastructure
        run: terraform apply -auto-approve
name: Terraform
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
